### ISSUE TITLE
localStorage not cleared (ios)

### ISSUE THREAD

**Issue by vgrafe** [ionic-team/ionic-view-issues#70]
Hi, it seems that using the "clear app data" button is not enough by itself since data stored in html5's localStorage is still cached/accessible. 

A workaround is to clear app data, logout, then login.

**Comment by GuyPie** [comment]
+1

**Comment by TillaTheHun0** [comment]
This workaround works for iOS. Does not work for Android however.

**Comment by xlozinguez** [comment]
+1 this actually doesn't work on iOS...

**Comment by ianbelcher** [comment]
Android workaround I found was to go into Android Settings -> Application manager -> Ionic View -> Clear data. Unfortunately blasts everything in the app but gets things working again if you're having troubles.

**Comment by TillaTheHun0** [comment]
@ianbelcher Clearing device cache worked for me as well. It's a workaround for now.

**Comment by TillaTheHun0** [comment]
@xlozinguez strange. It worked on View app v.1.0.5 on iPhone 6 running iOS 8.3. Try clearing app data, logout, clear app from background and *then* log back in. I didn't have to clear it from the background but worth a shot.

**Comment by ianbelcher** [comment]
@TillaTheHun0 You don't need to clear the entire cache, just for IV if you have the option to.

Just wondering if there is any progress or more info on this issue @tlancina? Ionic View is amazing for letting clients test out changes, but this issue throws up a lot of bugs (it appears as though Sync to Latest might suffer the same issues) and those bugs make the Client think you've introduced bad code. Otherwise, IV is amazing and appreciated!

**Comment by tlancina** [comment]
@ianbelcher this is fixed in the next release, which is sitting in the App Store review right now. Should be out in a week or two.

**Comment by ianbelcher** [comment]
Thanks @tlancina. Thats great news.

**Comment by rob212** [comment]
Amazing! Thanks @tlancina this is great news. Prevents having to uninstall the app each and every time you want to wipe localStorage. Good work.

**Comment by rob212** [comment]
The bug still seems to exist in Android. The workaround is described above by @ianbelcher but this is still a bit annoying. Any ideas if there is an update to the Ionic View app to address the local storage sandbox issue on Android like iOS ?

**Comment by novas1r1** [comment]
Any news on this? Still facing this issue on android... even if I'm deleting all ionic view data in the settings, the localStorage will not be cleared...

**Comment by RaviDasari** [comment]
Create a New ionic app and addd a button to it. That would run this javascript - 

```javascript
localStorage.clear()
```

and import it and reuse it.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
